# Generated by Django 5.1.7 on 2025-03-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvalidPolygonRecord',
        ),
    ]
